### ISSUE TITLE
URLs no readme não são acessíveis

### ISSUE THREAD

**Issue by jefersongoliveira** [pengovbr/mod-sei-estatisticas#24]
Prezado, bom dia. 
Precisamos fazer a integração com o SEI do MTE (https://processoeletronico.trabalho.gov.br) e não consegui acesso aos links abaixo:
1 - https://paineis.processoeletronico.gov.br/?view=governancagestor -> Retorna em branco

2 - Para solicitar a sua chave de conexão ou caso precise de ajuda, favor [abrir chamado em nossa Central de Atendimento](https://www.gov.br/economia/pt-br/assuntos/processo-eletronico-nacional/suporte-do-processo-eletronico-nacional). A URL informada me redireciona para "Conteúdo Restrito -  É necessário autenticar para visualizar essa página. Se você acredita que está recebendo essa mensagem incorretamente, por favor contate a [administração do site](https://www.gov.br/economia/pt-br/canais_atendimento/fale_conosco)." Informo que fiz a autenticação no Sou Gov.

Como devo proceder para o cadastro e ter acesso? Assim como é informado no readme : "Os campos url, sigla e chave devem ser preenchidos com os valores informados pela equipe do PEN, a partir de Chamado aberto na Central de Atendimento."

**Comment by marlinhares** [comment]
Olá @jefersongoliveira 
pode acessar o painel aqui:
https://paineis.processoeletronico.gov.br/painel.php?type=1&panel=db4326ef-2a08-4c09-aebb-e723bc7e0e0c&sheet=eefee2bf-b092-4d66-a7ab-8e738e06c9ac
(apenas dados de prd)

Para acesso pode abrir diretamente na nossa central de atendimento.
https://portaldeservicos.gestao.gov.br/pt#/


abcs
